# Generated by Django 5.2.8 on 2025-11-18 03:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("commit_sha", models.CharField(db_index=True, max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("push", "Push"),
                            ("pull_request", "Pull Request"),
                            ("scheduled", "Scheduled"),
                        ],
                        default="manual",
                        max_length=50,
                    ),
                ),
                ("sarif_file_path", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "sarif_file_size",
                    models.BigIntegerField(blank=True, help_text="Size in bytes", null=True),
                ),
                ("total_findings", models.IntegerField(default=0)),
                ("critical_count", models.IntegerField(default=0)),
                ("high_count", models.IntegerField(default=0)),
                ("medium_count", models.IntegerField(default=0)),
                ("low_count", models.IntegerField(default=0)),
                ("info_count", models.IntegerField(default=0)),
                (
                    "tools_used",
                    models.JSONField(
                        default=list, help_text="List of security tools used in this scan"
                    ),
                ),
                ("worker_id", models.CharField(blank=True, max_length=255, null=True)),
                ("worker_container_id", models.CharField(blank=True, max_length=255, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("error_details", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="organizations.branch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="organizations.organization",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="organizations.repository",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "scan",
                "verbose_name_plural": "scans",
                "db_table": "scans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScanLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("tool", models.CharField(blank=True, max_length=100, null=True)),
                ("context", models.JSONField(blank=True, null=True)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="scans.scan",
                    ),
                ),
            ],
            options={
                "verbose_name": "scan log",
                "verbose_name_plural": "scan logs",
                "db_table": "scan_logs",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="QuotaUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("year", models.IntegerField(db_index=True)),
                ("month", models.IntegerField(db_index=True)),
                ("scans_used", models.IntegerField(default=0)),
                ("storage_used_bytes", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quota_usage",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "quota usage",
                "verbose_name_plural": "quota usage",
                "db_table": "quota_usage",
                "ordering": ["-year", "-month"],
                "indexes": [
                    models.Index(
                        fields=["organization", "year", "month"],
                        name="quota_usage_organiz_f3b40d_idx",
                    )
                ],
                "unique_together": {("organization", "year", "month")},
            },
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(
                fields=["organization", "created_at"], name="scans_organiz_f5157a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(fields=["repository", "branch"], name="scans_reposit_f2fea7_idx"),
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(fields=["status"], name="scans_status_dc5ad7_idx"),
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(fields=["commit_sha"], name="scans_commit__434992_idx"),
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(fields=["created_at"], name="scans_created_363150_idx"),
        ),
        migrations.AddIndex(
            model_name="scanlog",
            index=models.Index(fields=["scan", "timestamp"], name="scan_logs_scan_id_ad7278_idx"),
        ),
        migrations.AddIndex(
            model_name="scanlog",
            index=models.Index(fields=["level"], name="scan_logs_level_931a79_idx"),
        ),
    ]
