# Generated by Django 5.2.8 on 2025-11-18 03:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("scans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("fingerprint", models.CharField(db_index=True, max_length=64)),
                ("rule_id", models.CharField(db_index=True, max_length=255)),
                ("rule_name", models.CharField(blank=True, max_length=512, null=True)),
                ("message", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("fixed", "Fixed"),
                            ("false_positive", "False Positive"),
                            ("accepted_risk", "Accepted Risk"),
                            ("wont_fix", "Won't Fix"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(max_length=1024)),
                ("start_line", models.IntegerField()),
                ("start_column", models.IntegerField(default=1)),
                ("end_line", models.IntegerField(blank=True, null=True)),
                ("end_column", models.IntegerField(blank=True, null=True)),
                ("snippet", models.TextField(blank=True, null=True)),
                ("tool_name", models.CharField(max_length=255)),
                ("tool_version", models.CharField(blank=True, max_length=100, null=True)),
                ("cwe_ids", models.JSONField(blank=True, default=list)),
                ("cve_ids", models.JSONField(blank=True, default=list)),
                (
                    "sarif_data",
                    models.JSONField(blank=True, help_text="Full SARIF result object", null=True),
                ),
                ("occurrence_count", models.IntegerField(default=1)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("fixed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "first_seen_scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings_first_seen",
                        to="scans.scan",
                    ),
                ),
                (
                    "last_seen_scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings_last_seen",
                        to="scans.scan",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="organizations.organization",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="organizations.repository",
                    ),
                ),
            ],
            options={
                "verbose_name": "finding",
                "verbose_name_plural": "findings",
                "db_table": "findings",
                "ordering": ["-severity", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FindingCluster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "cluster_label",
                    models.CharField(
                        db_index=True,
                        help_text="Cluster identifier (e.g., cluster_0, cluster_1)",
                        max_length=100,
                    ),
                ),
                ("size", models.IntegerField(default=0, help_text="Number of findings in cluster")),
                (
                    "avg_similarity",
                    models.FloatField(
                        default=0.0, help_text="Average pairwise similarity (0.0-1.0)"
                    ),
                ),
                (
                    "cohesion_score",
                    models.FloatField(
                        default=0.0, help_text="Cluster cohesion score (higher is better)"
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        default="dbscan", help_text="Clustering algorithm used", max_length=50
                    ),
                ),
                (
                    "similarity_threshold",
                    models.FloatField(
                        default=0.85, help_text="Similarity threshold used for clustering"
                    ),
                ),
                ("primary_rule_id", models.CharField(blank=True, max_length=255)),
                ("primary_severity", models.CharField(blank=True, max_length=20)),
                ("primary_tool", models.CharField(blank=True, max_length=255)),
                (
                    "statistics",
                    models.JSONField(
                        blank=True, default=dict, help_text="Detailed cluster statistics"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finding_clusters",
                        to="organizations.organization",
                    ),
                ),
                (
                    "representative_finding",
                    models.ForeignKey(
                        blank=True,
                        help_text="Most representative finding in cluster",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="representative_clusters",
                        to="findings.finding",
                    ),
                ),
            ],
            options={
                "verbose_name": "finding cluster",
                "verbose_name_plural": "finding clusters",
                "db_table": "finding_clusters",
                "ordering": ["-size", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FindingClusterMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "distance_to_centroid",
                    models.FloatField(
                        default=0.0, help_text="Distance from cluster centroid (lower is better)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="findings.findingcluster",
                    ),
                ),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cluster_memberships",
                        to="findings.finding",
                    ),
                ),
            ],
            options={
                "verbose_name": "finding cluster membership",
                "verbose_name_plural": "finding cluster memberships",
                "db_table": "finding_cluster_memberships",
            },
        ),
        migrations.CreateModel(
            name="FindingComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finding_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="findings.finding",
                    ),
                ),
            ],
            options={
                "verbose_name": "finding comment",
                "verbose_name_plural": "finding comments",
                "db_table": "finding_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="FindingStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("old_status", models.CharField(max_length=20)),
                ("new_status", models.CharField(max_length=20)),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finding_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="findings.finding",
                    ),
                ),
            ],
            options={
                "verbose_name": "finding status history",
                "verbose_name_plural": "finding status histories",
                "db_table": "finding_status_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LLMVerdict",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("true_positive", "True Positive"),
                            ("false_positive", "False Positive"),
                            ("uncertain", "Uncertain"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(help_text="Confidence score 0.0-1.0")),
                ("reasoning", models.TextField(help_text="LLM's explanation for the verdict")),
                (
                    "cwe_id",
                    models.CharField(
                        blank=True, help_text="CWE-XXX identified by LLM", max_length=50, null=True
                    ),
                ),
                (
                    "recommendation",
                    models.TextField(blank=True, help_text="LLM's fix recommendation", null=True),
                ),
                (
                    "llm_provider",
                    models.CharField(help_text="e.g., openai, anthropic", max_length=50),
                ),
                (
                    "llm_model",
                    models.CharField(help_text="e.g., gpt-4o, claude-sonnet-4", max_length=100),
                ),
                (
                    "agent_pattern",
                    models.CharField(
                        choices=[
                            ("post_processing", "Post-Processing Filter"),
                            ("interactive", "Interactive Retrieval"),
                            ("multi_agent", "Multi-Agent Collaboration"),
                        ],
                        default="post_processing",
                        help_text="Which agent pattern was used",
                        max_length=50,
                    ),
                ),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Estimated cost in USD",
                        max_digits=10,
                    ),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(help_text="Time taken for LLM call in milliseconds"),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True, help_text="Full LLM response for debugging", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_verdicts",
                        to="findings.finding",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM verdict",
                "verbose_name_plural": "LLM verdicts",
                "db_table": "llm_verdicts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["organization", "status"], name="findings_organiz_73b92b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(fields=["repository", "status"], name="findings_reposit_b4d329_idx"),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(fields=["fingerprint"], name="findings_fingerp_038764_idx"),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(fields=["severity"], name="findings_severit_c2e745_idx"),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(fields=["rule_id"], name="findings_rule_id_621dcf_idx"),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(fields=["first_seen_at"], name="findings_first_s_640f21_idx"),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["organization", "fingerprint"], name="findings_organiz_7f4e37_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="finding",
            unique_together={("organization", "fingerprint")},
        ),
        migrations.AddIndex(
            model_name="findingcluster",
            index=models.Index(
                fields=["organization", "cluster_label"], name="finding_clu_organiz_7e1d26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="findingcluster",
            index=models.Index(fields=["size"], name="finding_clu_size_5434a4_idx"),
        ),
        migrations.AddIndex(
            model_name="findingcluster",
            index=models.Index(fields=["created_at"], name="finding_clu_created_1e8cce_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="findingcluster",
            unique_together={("organization", "cluster_label")},
        ),
        migrations.AddIndex(
            model_name="findingclustermembership",
            index=models.Index(
                fields=["cluster", "distance_to_centroid"], name="finding_clu_cluster_95a004_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="findingclustermembership",
            unique_together={("finding", "cluster")},
        ),
        migrations.AddIndex(
            model_name="llmverdict",
            index=models.Index(
                fields=["finding", "created_at"], name="llm_verdict_finding_11dda3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="llmverdict",
            index=models.Index(fields=["verdict"], name="llm_verdict_verdict_d6ca96_idx"),
        ),
        migrations.AddIndex(
            model_name="llmverdict",
            index=models.Index(
                fields=["llm_provider", "llm_model"], name="llm_verdict_llm_pro_a71aa3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="llmverdict",
            index=models.Index(fields=["agent_pattern"], name="llm_verdict_agent_p_c211e0_idx"),
        ),
    ]
