# Generated by Django 5.2.8 on 2025-11-18 03:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "github_org_id",
                    models.CharField(blank=True, max_length=100, null=True, unique=True),
                ),
                ("github_org_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "scan_quota_monthly",
                    models.IntegerField(default=100, help_text="Monthly scan quota"),
                ),
                (
                    "storage_quota_gb",
                    models.IntegerField(default=10, help_text="Storage quota in GB"),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("starter", "Starter"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "organization",
                "verbose_name_plural": "organizations",
                "db_table": "organizations",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="organizatio_slug_5b8b37_idx"),
                    models.Index(fields=["github_org_id"], name="organizatio_github__b88f5f_idx"),
                    models.Index(fields=["created_at"], name="organizatio_created_8a4b5e_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("github_repo_id", models.CharField(db_index=True, max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=512)),
                ("default_branch", models.CharField(default="main", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_private", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repositories",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "repository",
                "verbose_name_plural": "repositories",
                "db_table": "repositories",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sha", models.CharField(max_length=40)),
                ("is_default", models.BooleanField(default=False)),
                ("is_protected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_scan_at", models.DateTimeField(blank=True, null=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="organizations.repository",
                    ),
                ),
            ],
            options={
                "verbose_name": "branch",
                "verbose_name_plural": "branches",
                "db_table": "branches",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                            ("viewer", "Viewer"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "organization membership",
                "verbose_name_plural": "organization memberships",
                "db_table": "organization_memberships",
                "indexes": [
                    models.Index(
                        fields=["organization", "user"], name="organizatio_organiz_cfed2c_idx"
                    ),
                    models.Index(fields=["user"], name="organizatio_user_id_db5190_idx"),
                    models.Index(fields=["role"], name="organizatio_role_e3a08a_idx"),
                ],
                "unique_together": {("organization", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["organization", "name"], name="repositorie_organiz_cc999f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(fields=["github_repo_id"], name="repositorie_github__05e23b_idx"),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(fields=["is_active"], name="repositorie_is_acti_c19d46_idx"),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(fields=["repository", "name"], name="branches_reposit_85246b_idx"),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(fields=["sha"], name="branches_sha_1a8a13_idx"),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(fields=["is_default"], name="branches_is_defa_1998a0_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="branch",
            unique_together={("repository", "name")},
        ),
    ]
